HotelBooking.Web/Models/ErrorViewModel.cs
namespace HotelBooking.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HotelBooking.Web/Controllers/HomeController.cs
using System.Diagnostics;
using HotelBooking.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace HotelBooking.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View();
        }
    }
}

HotelBooking.Web/Controllers/VillaController.cs
using HotelBooking.Domain.Entities;
using HotelBooking.Infrastructure.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Elfie.Serialization;

namespace HotelBooking.Web.Controllers
{
    public class VillaController : Controller
    {
        private readonly ApplicationDbContext _db;
        
        public VillaController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {  
            var villas = _db.Villas.ToList();
            return View(villas);
        }

        public IActionResult Create()
        {  
          
            return View( );
        }

        [HttpPost]
        public IActionResult Create(Villa obj)
        {
            if (ModelState.IsValid)
            {
                _db.Villas.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "The villa has been created successfully.";

                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Update(int villaId)
        {
            Villa? obj = _db.Villas.FirstOrDefault(u => u.Id == villaId);
            if (obj is null)
                return RedirectToAction("Error", "Home");

            return View(obj);
        }

        [HttpPost]
        public IActionResult Update(Villa obj)
        {
            _db.Villas.Update(obj);
            _db.SaveChanges();
            TempData["success"] = "The villa has been updated successfully.";
            return RedirectToAction("Index");
        }



        public IActionResult Delete(int villaId)
        {
            Villa? obj = _db.Villas.FirstOrDefault(u => u.Id == villaId);
            if (obj is null)
                return RedirectToAction("Error", "Home");

            return View(obj);
        }
        [HttpPost]
        public IActionResult Delete(Villa obj)
        {
            Villa? objFromDb = _db.Villas.FirstOrDefault(u => u.Id == obj.Id);
            if (objFromDb is not null)
           {
                _db.Villas.Remove(objFromDb);
                _db.SaveChanges();
                TempData["success"] = "The villa has been deleted successfully.";

                return RedirectToAction("Index");
            }
            return View(); 
        }

    }
}

HotelBooking.Web/Controllers/VillaNumberController.cs
using HotelBooking.Domain.Entities;
using HotelBooking.Infrastructure.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Elfie.Serialization;

namespace HotelBooking.Web.Controllers
{
    public class VillaNumberController : Controller
    {
        private readonly ApplicationDbContext _db;

        public VillaNumberController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var villaNumbers = _db.VillaNumbers.ToList();
            return View(villaNumbers);
        }

        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public IActionResult Create(VillaNumber obj)
        {
            if (ModelState.IsValid)
            {
                _db.VillaNumbers.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "The villaNumber has been created successfully.";

                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Update(int villaNumberId)
        {
            VillaNumber? obj = _db.VillaNumbers.FirstOrDefault(u => u.Equals(villaNumberId));
            if (obj is null)
                return RedirectToAction("Error", "Home");

            return View(obj);
        }

        [HttpPost]
        public IActionResult Update(VillaNumber obj)
        {
            _db.VillaNumbers.Update(obj);
            _db.SaveChanges();
            TempData["success"] = "The villa has been updated successfully.";
            return RedirectToAction("Index");
        }



        public IActionResult Delete(int villaNumberId)
        {
            VillaNumber? obj = _db.VillaNumbers.FirstOrDefault(u => u.Id == villaNumberId);
            if (obj is null)
                return RedirectToAction("Error", "Home");

            return View(obj);
        }
        [HttpPost]
        public IActionResult Delete(VillaNumber obj)
        {
            VillaNumber? objFromDb = _db.VillaNumbers.FirstOrDefault(u => u.Id == obj.Id);
            if (objFromDb is not null)
            {
                _db.VillaNumbers.Remove(objFromDb);
                _db.SaveChanges();
                TempData["success"] = "The villa has been deleted successfully.";

                return RedirectToAction("Index");
            }
            return View();
        }

    }
}

HotelBooking.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

HotelBooking.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HotelBooking.Web</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/css/bootstrap.min.css" integrity="sha512-jnSuA4Ss2PkkikSOLtYs8BlYIeeIK1h99ty4YfvRPAlzr377vr3CXDb7sb7eEEBYjDtcYj+AjBH3FLv5uSJuXg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/HotelBooking.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HotelBooking.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Villa" asp-action="">Villa</a>
                        </li><li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VillaNumber" asp-action="">VillaNumber</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - HotelBooking.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.min.js" integrity="sha512-ykZ1QQr0Jy/4ZkvKuqWn4iF3lqPZyij9iRv6sGqLRdTPkY69YX6+7wvVGmsdBbiIfN/8OdsI7HABjvEok6ZopQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HotelBooking.Web/Views/Shared/_Notification.cshtml
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}

HotelBooking.Web/Views/Villa/Create.cshtml
@{
    ViewData["Title"] = "Create";
}
@model HotelBooking.Domain.Entities.Villa

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Create Villa</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <div class="p-3">
                @* <div asp-validation-summary="All"></div>  *@
                <div class="form-floating py-1 col-12">
                    <input asp-for="Name" class="form-control border shadow" />
                    <label asp-for="Name" class="ms-2"></label>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Description" class="form-control border shadow" />
                    <label asp-for="Description" class="ms-2"></label>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Price" class="form-control border shadow" />
                    <label asp-for="Price" class="ms-2"></label>
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Sqft" class="form-control border shadow" />
                    <label asp-for="Sqft" class="ms-2"></label>
                    <span asp-validation-for="Sqft" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Occupancy" class="form-control border shadow" />
                    <label asp-for="Occupancy" class="ms-2"></label>
                    <span asp-validation-for="Occupancy" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="ImageUrl" hidden class="form-control border shadow" />
                    @* <input asp-for="Image" class="form-control border shadow" /> *@
                    <input asp-for="ImageUrl" class="form-control border shadow" />
                    <label asp-for="ImageUrl" class="ms-2 "></label>
                    <span asp-validation-for="ImageUrl" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <i class="bi bi-check-circle"></i> Create
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

HotelBooking.Web/Views/Villa/Delete.cshtml
@model HotelBooking.Domain.Entities.Villa

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Delete Villa</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row">
            <input asp-for="Id" hidden />
            <div class="col-10">
                <div class="p-3">
                    @* <div asp-validation-summary="All"></div> *@
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Name" disabled class="form-control border shadow" />
                        <label asp-for="Name" class="ms-2"></label>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Description" disabled class="form-control border shadow" />
                        <label asp-for="Description" class="ms-2"></label>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Price" disabled class="form-control border shadow" />
                        <label asp-for="Price" class="ms-2"></label>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Sqft" disabled class="form-control border shadow" />
                        <label asp-for="Sqft" class="ms-2"></label>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Occupancy" disabled class="form-control border shadow" />
                        <label asp-for="Occupancy" class="ms-2"></label>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="ImageUrl" disabled class="form-control border shadow" />
                        <label asp-for="ImageUrl" class="ms-2"></label>
                    </div>
                    <div class="row pt-2">
                        <div class="col-6 col-md-3">
                            <button type="submit" class="btn btn-danger w-100">
                                <i class="bi bi-trash-fill"></i> Delete
                            </button>
                        </div>
                        <div class="col-6 col-md-3">
                            <a asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100">
                                <i class="bi bi-x-circle"></i> Cancel
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-2">
                <img src="@Model.ImageUrl" width="100%"
                     style="border-radius:5px; border:1px solid #bbb9b9" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

HotelBooking.Web/Views/Villa/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@model IEnumerable<HotelBooking.Domain.Entities.Villa>

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Villa List</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <div class="row pb-3">
            <div class="col-6 offset-6 text-end">
                <a asp-controller="Villa" asp-action="Create" class="btn btn-secondary">
                    <i class="bi bi-plus-circle"></i> Create New Villa
                </a>
            </div>
        </div>

        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>Price</th>
                    <th>Sqft</th>
                    <th>Occupancy</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td>@obj.Name</td>
                        <td>@obj.Price</td>
                        <td>@obj.Sqft</td>
                        <td>@obj.Occupancy</td>
                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Villa" asp-action="Update" asp-route-villaId="@obj.Id"
                                   class="btn btn-success mx-2">
                                    <i class="bi bi-pencil-square"></i> Edit
                                </a>
                                <a asp-controller="Villa" asp-action="Delete" asp-route-villaId="@obj.Id"
                                   class="btn btn-danger mx-2">
                                    <i class="bi bi-trash-fill"></i> Delete
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

HotelBooking.Web/Views/Villa/Update.cshtml
@model HotelBooking.Domain.Entities.Villa

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Update Villa</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="Id" hidden />
            <div class="col-10">
                <div class="p-3">
                    @* <div asp-validation-summary="All"></div> *@
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Name" class="form-control border shadow" />
                        <label asp-for="Name" class="ms-2"></label>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Description" class="form-control border shadow" />
                        <label asp-for="Description" class="ms-2"></label>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Price" class="form-control border shadow" />
                        <label asp-for="Price" class="ms-2"></label>
                        <span asp-validation-for="Price" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Sqft" class="form-control border shadow" />
                        <label asp-for="Sqft" class="ms-2"></label>
                        <span asp-validation-for="Sqft" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Occupancy" class="form-control border shadow" />
                        <label asp-for="Occupancy" class="ms-2"></label>
                        <span asp-validation-for="Occupancy" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        @* <input asp-for="Image"  class="form-control border shadow" /> *@
                        <input asp-for="ImageUrl" hidden class="form-control border shadow" />
                        <input asp-for="ImageUrl"  class="form-control border shadow" />
                        <label asp-for="ImageUrl" class="ms-2"></label>
                        <span asp-validation-for="ImageUrl" class="text-danger"></span>
                    </div>
                    <div class="row pt-2">
                        <div class="col-6 col-md-3">
                            <button type="submit" class="btn btn-success w-100">
                                <i class="bi bi-check-circle"></i> Update
                            </button>
                        </div>
                        <div class="col-6 col-md-3">
                            <a asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100">
                                <i class="bi bi-x-circle"></i> Cancel
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-2">
                <img src="@Model.ImageUrl" width="100%"
                     style="border-radius:5px; border:1px solid #bbb9b9" />
            </div>

        </form>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

HotelBooking.Web/Views/VillaNumber/Create.cshtml
@model VillaNumber

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Create Villa Number</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row">
            <div class="p-3">
                @* <div asp-validation-summary="All"></div>  *@
                <div class="form-floating py-1 col-12">
                    <input asp-for="Id" class="form-control border shadow" />
                    <label asp-for="Id" class="ms-2"></label>
                    <span asp-validation-for="Id" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Villa_Number" class="form-control border shadow" />
                    <label asp-for="Villa_Number" class="ms-2"></label>
                    <span asp-validation-for="Villa_Number" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="SpecialDetails" class="form-control border shadow" />
                    <label asp-for="SpecialDetails" class="ms-2"></label>
                    <span asp-validation-for="SpecialDetails" class="text-danger"></span>
                </div>
       
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <i class="bi bi-check-circle"></i> Create
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="VillaNumber" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

HotelBooking.Web/Views/VillaNumber/Index.cshtml
@model IEnumerable<VillaNumber>

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Villa Number List</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <div class="row pb-3">
            <div class="col-6 offset-6 text-end">
                <a asp-controller="VillaNumber" asp-action="Create" class="btn btn-secondary">
                    <i class="bi bi-plus-circle"></i> Create New Villa Number
                </a>
            </div>
        </div>

        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
                        Villa Name
                    </th>
                    <th>Villa Number</th>
                    <th>Specials Details</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td>@obj.Id</td>
                        <td>@obj.Villa_Number</td>
                        <td>@obj.SpecialDetails</td>
                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="VillaNumber" asp-action="Update" asp-route-villaNumberId="@obj.Villa_Number"
                                   class="btn btn-success mx-2">
                                    <i class="bi bi-pencil-square"></i> Edit
                                </a>
                                <a asp-controller="VillaNumber" asp-action="Delete" asp-route-villaNumberId="@obj.Villa_Number"
                                   class="btn btn-danger mx-2">
                                    <i class="bi bi-trash-fill"></i> Delete
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>